"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Player_js_1 = require("./classes/Player.js");
var mashrafi = new Player_js_1.Player('Mashrafi', 40, 'Bangladesh');
var sakib = new Player_js_1.Player('Sakib', 37, 'Bangladesh');
console.log(sakib.age);
// sakib.country = 'England';
console.log(sakib.country);
var players = [];
players.push(sakib);
players.push(mashrafi);
console.log(players);
